# Generated by Django 4.2.10 on 2024-02-21 15:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('duration', models.DurationField(help_text='Estimated duration of the service')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=100)),
                ('dog_breed', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_booking', models.DateField()),
                ('appointment_time', models.TimeField(choices=[(datetime.time(9, 0), '9:00am'), (datetime.time(9, 30), '9:30am'), (datetime.time(10, 0), '10:00am'), (datetime.time(10, 30), '10:30am'), (datetime.time(11, 0), '11:00am'), (datetime.time(11, 30), '11:30am'), (datetime.time(12, 0), '12:00pm'), (datetime.time(12, 30), '12:30pm'), (datetime.time(13, 0), '1:00pm'), (datetime.time(13, 30), '1:30pm'), (datetime.time(14, 0), '2:00pm'), (datetime.time(14, 30), '2:30pm'), (datetime.time(15, 0), '3:00pm'), (datetime.time(15, 30), '3:30pm'), (datetime.time(16, 0), '4:00pm'), (datetime.time(16, 30), '4:30pm')])),
                ('confirmed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=0)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_name_booking', to='booking_system.services')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service_name', 'date_of_booking', 'appointment_time'],
            },
        ),
    ]
