# Generated by Django 4.2.10 on 2024-02-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['service_name', 'cost', 'duration']},
        ),
    ]
