# Generated by Django 4.2.10 on 2024-03-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_alter_services_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['service_name', 'description', 'cost', 'duration']},
        ),
        migrations.AlterField(
            model_name='services',
            name='cost',
            field=models.TextField(help_text="Enter the cost range depending on dog size, e.g., 'Small Dogs: £35, Large Dogs: £100'"),
        ),
    ]
